Repository azu/ni.zsh, pull requests merged in 2023-08, with the labels that each got.

#3 fix: README to work with sheldon
  README.md
Labels: documentation

#9 refactor: Add `ni-` prefix to each function
  ni.zsh
Labels: Type: Refactoring

#10 fix: remove duplicated risks
  ni.zsh
Labels: Type: Bug

#12 feat: support `bun update <pkg>`
  README.md
  ni.zsh
Labels: Type: Feature
